# Generated by Django 3.2.5 on 2022-02-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220214_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
