# Generated by Django 3.2.5 on 2022-02-17 13:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='venue_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
