# Generated by Django 3.2.5 on 2022-02-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_events_venue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Event Time'),
        ),
    ]
