# Generated by Django 3.2.5 on 2022-02-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_events_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event Date'),
        ),
    ]
