# Generated by Django 3.2.5 on 2022-02-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_events_event_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': 'Event'},
        ),
        migrations.RemoveField(
            model_name='events',
            name='guest_limit',
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='events',
            name='venue',
            field=models.CharField(max_length=150),
        ),
    ]
