# Generated by Django 3.2.5 on 2022-02-19 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_auto_20220219_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='events_guests', to=settings.AUTH_USER_MODEL),
        ),
    ]
