# Generated by Django 3.2.13 on 2022-06-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20220616_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_emails',
            new_name='Contact_mails',
        ),
    ]
